Add route verify
loozzi/agile-line pull request #22
Opened 2024-03-26 16:52 UTC by VuThanhDat14122004

- Add route **/verify** in src/controllers/auth_controller.py
- Add function **verify** in src/services/auth_service.py

2024-03-27 07:54 UTC, loozzi requested changes
chỉnh sửa file `auth_controller` và file `auth_service`

2024-03-27 07:54 UTC, loozzi commented on backend/src/controllers/auth_controller.py
- Đặt middleware token_required ở các route cần phải đăng nhập
- Bỏ try except ở route send_otp

2024-03-27 07:54 UTC, loozzi commented on backend/src/services/auth_service.py
- Xóa middleware `token_required` ở các hàm
- Sửa lại hàm `send_otp`: Xóa try except và xử lí response thông qua dữ liệu trả về từ hàm `send_otp_email`
- Refactor code: Hàm `login` và hàm `verify` có điểm chung là generate token và trả về data => tạo hàm mới để xử lí
- Chưa thực hiện lưu Otp vào trong database

2024-03-27 17:19 UTC, VuThanhDat14122004 commented on backend/src/controllers/auth_controller.py
- The `token_required` middleware has been applied to routes that require authentication
- The `try-except` block has been removed from the `send_otp` route

2024-03-27 17:26 UTC, VuThanhDat14122004 commented on backend/src/services/auth_service.py
- The `token_required` middleware has been removed from functions
- The `send_otp` has been edited: except has been deleted and respone has been processed through `send_otp_email` function
- The Otp has been saved to database

2024-03-27 17:34 UTC, loozzi reviewed
- Khôi phục file _login_requried_
- Sửa file _auth_service_

2024-03-27 17:34 UTC, loozzi commented on backend/src/middlewares/login_required.py
Sao lại xóa `.split(" ")[1]` ở đoạn `token = request.headers["Authorization"].split(" ")[1]`

2024-03-27 17:34 UTC, loozzi commented on backend/src/services/auth_service.py
refactor lại hàm `send_otp` phần gọi hàm `send_otp_email()`, nên xử lí gọi hàm 1 lần thôi

2024-03-28 07:10 UTC, loozzi approved these changes

2024-03-28 07:10 UTC, merged